# Generated by Django 2.0.9 on 2018-11-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_kitchen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnitures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.TextField()),
            ],
        ),
    ]
