# Generated by Django 2.0.9 on 2018-11-21 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_plasticmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.TextField()),
                ('launch_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
