# Generated by Django 2.0.9 on 2018-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicgadgets',
            name='prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plasticmaterials',
            name='prize',
            field=models.IntegerField(default=0),
        ),
    ]
